#!/usr/bin/env python3
"""
Setup script for AI Video Editor.

This script helps users configure the application by:
1. Creating a virtual environment
2. Installing dependencies
3. Setting up environment variables (Grok API key, etc.)
4. Guiding through YouTube OAuth setup
"""

import os
import sys
import subprocess
from pathlib import Path

def print_header(text):
    """Print a formatted header."""
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60 + "\n")

def print_step(step_num, text):
    """Print a formatted step."""
    print(f"\n[Step {step_num}] {text}")
    print("-" * 60)

def run_command(cmd, check=True):
    """Run a shell command."""
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if check and result.returncode != 0:
        print(f"❌ Error: {result.stderr}")
        sys.exit(1)
    return result

def check_python_version():
    """Check if Python 3.11+ is available."""
    print_step(1, "Checking Python version...")
    version = sys.version_info
    if version.major < 3 or (version.major == 3 and version.minor < 11):
        print("❌ Python 3.11 or higher is required")
        print(f"   Current version: {version.major}.{version.minor}.{version.micro}")
        sys.exit(1)
    print(f"✅ Python {version.major}.{version.minor}.{version.micro} detected")

def setup_venv():
    """Set up virtual environment."""
    print_step(2, "Setting up virtual environment...")
    venv_path = Path(__file__).parent / 'venv'
    
    if venv_path.exists():
        response = input("Virtual environment already exists. Recreate? (y/N): ").strip().lower()
        if response == 'y':
            import shutil
            shutil.rmtree(venv_path)
            print("Removed existing virtual environment")
        else:
            print("Using existing virtual environment")
            return
    
    print("Creating virtual environment...")
    run_command(f"{sys.executable} -m venv venv")
    print("✅ Virtual environment created")

def install_dependencies():
    """Install Python dependencies."""
    print_step(3, "Installing dependencies...")
    
    # Determine the correct pip path
    if sys.platform == 'win32':
        pip_path = Path(__file__).parent / 'venv' / 'Scripts' / 'pip'
    else:
        pip_path = Path(__file__).parent / 'venv' / 'bin' / 'pip'
    
    print("This may take several minutes...")
    print("Installing packages: Flask, Whisper, YOLO, MoviePy, and more...")
    
    result = run_command(f"{pip_path} install --upgrade pip", check=False)
    run_command(f"{pip_path} install -r requirements.txt")
    
    print("✅ Dependencies installed")

def setup_environment_variables():
    """Set up environment variables."""
    print_step(4, "Setting up environment variables...")
    
    env_file = Path(__file__).parent / '.env'
    
    if env_file.exists():
        response = input(".env file already exists. Overwrite? (y/N): ").strip().lower()
        if response != 'y':
            print("Keeping existing .env file")
            return
    
    print("\n📝 Environment Variables Setup")
    print("You can skip any of these and set them later in the .env file")
    print()
    
    env_vars = {}
    
    # Grok API Key
    print("🤖 Grok API Key (optional but recommended for AI processing)")
    print("   Get it from: https://console.x.ai/")
    grok_key = input("   Enter Grok API Key (or press Enter to skip): ").strip()
    if grok_key:
        env_vars['GROK_API_KEY'] = grok_key
    
    # Port
    print("\n🌐 Application Port")
    port = input("   Enter port number (default: 8080): ").strip()
    if port:
        env_vars['PORT'] = port
    else:
        env_vars['PORT'] = '8080'
    
    # Write .env file
    with open(env_file, 'w') as f:
        f.write("# AI Video Editor Environment Variables\n")
        f.write("# Generated by setup.py\n\n")
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print(f"\n✅ Environment variables saved to .env")
    if grok_key:
        print("   ✓ Grok API Key configured")
    else:
        print("   ⚠ Grok API Key not set (you can add it later)")

def setup_youtube_oauth():
    """Guide user through YouTube OAuth setup."""
    print_step(5, "YouTube OAuth Setup")
    
    print("\n📺 YouTube Account Authentication")
    print("You have two options:")
    print()
    print("Option 1: Web-based Authentication (Recommended)")
    print("  - Start the app and go to http://localhost:8080/accounts")
    print("  - Click 'Authenticate with YouTube'")
    print("  - Follow the OAuth flow in your browser")
    print()
    print("Option 2: Manual Credential Upload")
    print("  - Download OAuth2 credentials from Google Cloud Console")
    print("  - Go to http://localhost:8080/accounts")
    print("  - Upload the credentials file")
    print()
    
    response = input("Do you have OAuth2 credentials ready now? (y/N): ").strip().lower()
    if response == 'y':
        print("\n📋 Instructions:")
        print("1. Go to Google Cloud Console: https://console.cloud.google.com/")
        print("2. Create a project (or select existing)")
        print("3. Enable YouTube Data API v3")
        print("4. Go to 'Credentials' → 'Create Credentials' → 'OAuth client ID'")
        print("5. Choose 'Desktop app' as application type")
        print("6. Download the JSON file")
        print("7. After starting the app, upload it at http://localhost:8080/accounts")
        print()
        input("Press Enter when ready to continue...")
    
    print("\n✅ YouTube OAuth setup instructions provided")
    print("   You can complete this after starting the application")

def check_system_dependencies():
    """Check for system dependencies."""
    print_step(6, "Checking system dependencies...")
    
    # Check for ffmpeg
    result = run_command("which ffmpeg", check=False)
    if result.returncode == 0:
        print("✅ ffmpeg found")
    else:
        print("⚠️  ffmpeg not found")
        print("   Install with: brew install ffmpeg (macOS) or apt-get install ffmpeg (Linux)")
    
    # Check for cmake (needed for some packages)
    result = run_command("which cmake", check=False)
    if result.returncode == 0:
        print("✅ cmake found")
    else:
        print("⚠️  cmake not found (may be needed for some dependencies)")
        print("   Install with: brew install cmake (macOS)")

def print_next_steps():
    """Print next steps for the user."""
    print_header("Setup Complete! 🎉")
    
    print("Next steps:")
    print()
    print("1. Start the application:")
    print("   source venv/bin/activate  # On macOS/Linux")
    print("   .\\venv\\Scripts\\activate  # On Windows")
    print("   ./run.sh                  # Or: python app.py")
    print()
    print("2. Open your browser:")
    print("   http://localhost:8080")
    print()
    print("3. Add YouTube accounts:")
    print("   http://localhost:8080/accounts")
    print()
    print("4. Start creating YouTube Shorts!")
    print()
    print("📚 Documentation:")
    print("   - README.md - Full documentation")
    print("   - LOGGING.md - Logging information")
    print("   - logs/ - Application logs")
    print()

def main():
    """Main setup function."""
    print_header("AI Video Editor - Setup")
    
    print("This script will:")
    print("  ✓ Check Python version")
    print("  ✓ Create virtual environment")
    print("  ✓ Install dependencies")
    print("  ✓ Set up environment variables")
    print("  ✓ Guide you through YouTube OAuth setup")
    print()
    
    response = input("Continue with setup? (Y/n): ").strip().lower()
    if response == 'n':
        print("Setup cancelled.")
        sys.exit(0)
    
    try:
        check_python_version()
        setup_venv()
        install_dependencies()
        setup_environment_variables()
        check_system_dependencies()
        setup_youtube_oauth()
        print_next_steps()
        
    except KeyboardInterrupt:
        print("\n\nSetup interrupted by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == '__main__':
    main()

